In [27]:
"""PyAudio Example: Play a wave file."""
import wave, pyaudio
import os
os.environ['SDL_AUDIODRIVER'] = 'dsp'

def play_wav(wav_name, output_device_index=None):
	p = pyaudio.PyAudio()
	with wave.open(wav_name, 'rb') as wf:
		stream = p.open(format=p.get_format_from_width(wf.getsampwidth()),
					channels=wf.getnchannels(),
					rate=wf.getframerate(),
					output=True,
					output_device_index=output_device_index)
		while len(data := wf.readframes(1024)):
			stream.write(data)
		stream.close()
		p.terminate()

In [3]:
play_wav("voice/short.wav")

ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2

2
2
44100


In [19]:
import soundfile as sf
data, samplerate = sf.read('voice/short.wav', dtype='float32')
len(data) / samplerate, data.shape

(3.1956462585034013, (140928, 2))

In [18]:
with wave.open('voice/short.wav', 'rb') as wf:
    data_block = wf.readframes(1024)

In [36]:
import struct

# Input binary data
binary_data = b'\x40\x49\x0f\xdb'
# Unpack the binary data as a 32-bit float
unpacked_float = struct.unpack('f', binary_data)[0]

print(unpacked_float)

-4.03314608963584e+16


In [50]:
import struct

data[0,0], struct.unpack("<l", data_block[:4])

(-0.059020996, (-126683022,))

In [55]:
data_block[:4]

b'r\xf8r\xf8'

In [74]:
with open('voice/short.wav', 'rb') as f:
    header = f.read(44)

In [11]:
class WavInfo:
    """Class for storing wav parameters to pass to pyaudio"""
    frame_rate: int
    num_channels: int
    sample_width: int

    def __init__(self, frame) -> float:
        print(frame)
        assert(len(frame)==44)
        assert(frame[0:4]==b'RIFF')
        wav_size = struct.unpack('I', frame[4:8])[0]
        assert(frame[8:12]==b'WAVE')
        assert(frame[12:16]==b'fmt ')
        assert(struct.unpack('I', frame[16:20])[0] == 16)
        format_tag, num_channels = struct.unpack('2h', frame[20:24])
        sample_rate, byte_rate = struct.unpack('2I', frame[24:32])
        block_align, bits_per_sample = struct.unpack('2h', frame[32:36])
        assert(byte_rate == block_align * sample_rate)
        assert(frame[36:40]==b'data')
        data_size = struct.unpack('I', frame[40:44])[0]
        assert(wav_size == data_size + 36)

        self.sample_width = bits_per_sample // 8
        self.frame_rate = sample_rate
        self.num_channels = num_channels
        # num_samples = data_size // (num_channels * sample_width)

import wave, pyaudio
import os, struct
os.environ['SDL_AUDIODRIVER'] = 'dsp'

def play_wav2(wav_name, CHUNK=1024):
    p = pyaudio.PyAudio()

    stream = None
    with open(wav_name, 'rb') as wf:
        while (len(block := wf.read(CHUNK))):
            if stream is None:
                header = WavInfo(block[:44])
                stream = p.open(format=p.get_format_from_width(header.sample_width),
						channels=header.num_channels,
						rate=header.frame_rate,
						output=True)
                data = block[44:]
            else:
                data = block
            stream.write(data)
        stream.close()
    p.terminate()

play_wav2("voice/short.wav")

ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2

b'RIFF$\x9a\x08\x00WAVEfmt \x10\x00\x00\x00\x01\x00\x02\x00D\xac\x00\x00\x10\xb1\x02\x00\x04\x00\x10\x00data\x00\x9a\x08\x00'


In [17]:
with wave.open('voice/short.wav', 'rb') as wf:
	total_len = 0
	while len(data := wf.readframes(1024)):
		total_len += len(data)
total_len // 4

140928

In [24]:
import torchaudio

sent_file = '/home/zipa/Documents/kapitza_bot/audio-tcp/voice/1.wav'
rcvd_file = '/home/zipa/Documents/kapitza_bot/.received/ay7slazh.wav'

data1 = open(sent_file, 'rb').read()
data2 = open(rcvd_file, 'rb').read()
# assert(data1[:98092] == data2[:98092])
len(data1), len(data2)

(98092, 1024)

In [27]:
# re-encoding with torchaudio
# generates noises
import torchaudio

data = torchaudio.load('voice/3.wav')
torchaudio.save('voice/3.wav', data[0], data[1], encoding="PCM_U", backend="soundfile")
play_wav('voice/3.wav')

ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2

1
1
24000


Record Audio Using System Microphone
[OnWindows](https://stackoverflow.com/questions/26573556/record-speakers-output-with-pyaudio)

In [21]:
import pyaudio, os

os.environ['SDL_AUDIODRIVER'] = 'dsp'
p = pyaudio.PyAudio()

def print_input_devices(p: pyaudio.PyAudio):
    for i in range(p.get_device_count()):
        device_info = p.get_device_info_by_index(i)
        if device_info['maxInputChannels'] > 0:
            print(device_info)

def print_output_devices(p: pyaudio.PyAudio):
    for i in range(p.get_device_count()):
        device_info = p.get_device_info_by_index(i)
        if device_info['maxOutputChannels'] > 0:
            print(device_info)

print_input_devices(p)
print_output_devices(p)

{'index': 0, 'structVersion': 2, 'name': 'HD Webcam C525: USB Audio (hw:0,0)', 'hostApi': 0, 'maxInputChannels': 1, 'maxOutputChannels': 0, 'defaultLowInputLatency': 0.007979166666666667, 'defaultLowOutputLatency': -1.0, 'defaultHighInputLatency': 0.032, 'defaultHighOutputLatency': -1.0, 'defaultSampleRate': 48000.0}
{'index': 1, 'structVersion': 2, 'name': 'AIMIC-M4: USB Audio (hw:1,0)', 'hostApi': 0, 'maxInputChannels': 2, 'maxOutputChannels': 2, 'defaultLowInputLatency': 0.007979166666666667, 'defaultLowOutputLatency': 0.007979166666666667, 'defaultHighInputLatency': 0.032, 'defaultHighOutputLatency': 0.032, 'defaultSampleRate': 48000.0}
{'index': 2, 'structVersion': 2, 'name': 'HDA Intel PCH: ALC897 Analog (hw:2,0)', 'hostApi': 0, 'maxInputChannels': 2, 'maxOutputChannels': 2, 'defaultLowInputLatency': 0.005804988662131519, 'defaultLowOutputLatency': 0.005804988662131519, 'defaultHighInputLatency': 0.034829931972789115, 'defaultHighOutputLatency': 0.034829931972789115, 'defaultSamp

ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2

In [29]:
def output_stream_for_device(dev_index):
    device_info = p.get_device_info_by_index(dev_index)
    if device_info['maxOutputChannels'] == 0:
        print(f"Can not use device {dev_index} for output")
        return None
    stream = p.open(format = p.get_format_from_width(2),
                    channels = 2 if device_info['maxOutputChannels'] > 2 else 1,
                    rate = int(device_info['defaultSampleRate']),
                    output = True,
                    output_device_index = dev_index,
                    frames_per_buffer = 1024)
    return stream

for dev_index in range(p.get_device_count()):
    device_info = p.get_device_info_by_index(dev_index)
    if device_info['maxOutputChannels'] == 0:
        print(f"Can not use device {dev_index} for output")
        continue
    print(f"Playing using device {dev_index} for output")
    try:
        play_wav("voice/short.wav", output_device_index=dev_index)
    except Exception as e:
        print(f"{e}")
        continue

target_output_device = 12

Can not use device 0 for output
Playing using device 1 for output
[Errno -9985] Device unavailable
Playing using device 2 for output


Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->playback, alsaApi, outParams, StreamDirection_Out, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2175
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2839


Can not use device 3 for output
Playing using device 4 for output
Playing using device 5 for output
Playing using device 6 for output
Playing using device 7 for output
Can not use device 8 for output
Can not use device 9 for output
Can not use device 10 for output
Can not use device 11 for output
Playing using device 12 for output
Can not use device 13 for output
Can not use device 14 for output
Playing using device 15 for output


In [2]:
import io
in_memory = io.BytesIO()
in_memory.write(b' world')
in_memory.seek(0)  # go to the start of the stream
print(in_memory.read())

b' world'


In [2]:
"""PyAudio Example: Play a wave file."""
import pyaudio
import os
from connection.buffer import WavInfo

os.environ['SDL_AUDIODRIVER'] = 'dsp'

def play_wav2(wav_name, CHUNK=1024):
    p = pyaudio.PyAudio()

    stream = None
    with open(wav_name, 'rb') as wf:
        while (len(block := wf.read(CHUNK))):
            if stream is None:
                header_bytes, block = block[:44], block[44:]
                header = WavInfo(header_bytes, verbose=False)
                print(header.sample_width, p.get_format_from_width(
                    header.sample_width))
                stream = p.open(format=2 if header.sample_width == 4 else p.get_format_from_width(
                        header.sample_width),
                        channels=header.num_channels,
                        rate=header.frame_rate,
                        frames_per_buffer=CHUNK,
                        output=True)
                stream.start_stream()
            if len(block):
                stream.write(block)
        stream.stop_stream()
        stream.close()
    p.terminate()

play_wav2("voice/short.wav")
play_wav2(".received_feedback/az63rhl3.wav")

2 8
4 1


In [8]:
# import os
# os.chdir('..')
import time
from utils.logger import logger, log_mode

class Pipeline:
    def __init__(self,
                 log = False):
        global log_mode
        if log:
            log_mode = "s"

    @logger
    def set_user(self, user_name):
        time.sleep(1)

    @logger
    def process(self):
        time.sleep(3)

demo_class = Pipeline(log=True)
demo_class.set_user("вася")
demo_class.process()

In [2]:
!pip3 install -U funasr

  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 677.8/677.8 kB 2.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 4.1 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 7.7 MB/s eta 0:00:00a 0:00:01
  Created wheel for jaconv: filename=jaconv-0.4.0-py3-none-any.whl size=18227 sha256=96d5bc41bfdf7cc10b8e8fb7d46afdf91c492aa9167a5b11b2d92c19f2990fc4
  Stored in directory: /home/zipa/.cache/pip/wheels/1c/63/71/95fb322fe9047ed7e61b007c47cbf03d23ecb77dd03665f151
  Created wheel for oss2: filename=oss2-2.19.1-py3-none-any.whl size=123942 sha256=1dd04c079720f20bbc2403e499e713cf8dfb77b1b5d314b2859767c21a762355
  Stored in directory: /home/zipa/.cache/pip/wheels/56/27/a3/50e7db0dd68810d9d4e383a547b88b4a5b1eaae58e63c1d64a
  Created wheel for aliyun-python-sdk-core: filename=al

In [9]:
from funasr import AutoModel

# model = AutoModel(model="iic/speech_campplus_sv_zh-cn_16k-common", hub="hf")
model = AutoModel(model="funasr/campplus", hub="hf")

emb1 = model.generate(input="../.generated/color_0.wav")[0]['spk_embedding']
emb2 = model.generate(input="../.generated/color_1.wav")[0]['spk_embedding']
emb3 = model.generate(input="../files/name1.wav")[0]['spk_embedding']
emb4 = model.generate(input="../files/color.wav")[0]['spk_embedding']
emb5 = model.generate(input="../files/test.wav")[0]['spk_embedding']


funasr version: 1.1.14.
Check update of funasr, and it would cost few times. You may disable it by set `disable_update=True` in AutoModel
You are using the latest version of funasr-1.1.14


Fetching 8 files: 100%|██████████| 8/8 [00:00<00:00, 182361.04it/s]
/home/zipa/miniconda3/envs/kapitza/lib/python3.11/site-packages/funasr/train_utils/load_pretrained_model.py:39: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub fo

In [12]:
import torch
torch.cosine_similarity(emb1, emb2), torch.cosine_similarity(emb1, emb3), torch.cosine_similarity(emb1, emb5)

(tensor([0.8875], device='cuda:0'),
 tensor([-0.0782], device='cuda:0'),
 tensor([0.0250], device='cuda:0'))

In [11]:
torch.cosine_similarity(emb2, emb3), torch.cosine_similarity(emb3, emb4), torch.cosine_similarity(emb4, emb5) 

(tensor([0.0204], device='cuda:0'),
 tensor([0.4920], device='cuda:0'),
 tensor([0.0622], device='cuda:0'))

In [ ]:
# instantiate the pipeline
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained(
  "pyannote/speaker-diarization-3.1",
  use_auth_token="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")

# run the pipeline on an audio file
diarization = pipeline("../files/name1.wav")

# dump the diarization output to disk using RTTM format
# with open("audio.rttm", "w") as rttm:
#     diarization.write_rttm(rttm)

In [ ]:
from llama_index.core.memory import ChatMemoryBuffer
from llama_index.core.chat_engine import CondensePlusContextChatEngine
from llama_index.llms.llama_cpp import LlamaCPP
from llama_index.llms.llama_cpp.llama_utils import ( messages_to_prompt_v3_instruct, completion_to_prompt_v3_instruct)


class LLMProcessor:
    def __init__(self):
        llm = LlamaCPP(
            # You can pass in the URL to a GGML model to download it automatically
            model_url="https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct.Q4_K_M.gguf",
            # optionally, you can set the path to a pre-downloaded model instead of model_url
            model_path=None,
            temperature=0.05,
            max_new_tokens=256,
            context_window=4096,
            # kwargs to pass to __call__()
            generate_kwargs={},
            # kwargs to pass to __init__()
            # set to at least 1 to use GPU
            model_kwargs={"n_gpu_layers": 33},
            # transform inputs into Llama2 format
            messages_to_prompt=messages_to_prompt_v3_instruct, # messages_to_prompt_qwen,
            completion_to_prompt=completion_to_prompt_v3_instruct, # completion_to_prompt_qwen,
            verbose=False,
        )
        memory = ChatMemoryBuffer.from_defaults(token_limit=3900)
        self.chat_engine = CondensePlusContextChatEngine.from_defaults(
            None, 
            memory=memory,
            llm=llm,
            context_prompt=(
                "You are a chatbot, able to have normal interactions, as well as talk"
                " about the Kendrick and Drake beef."
                "Here are the relevant documents for the context:\n"
                "{context_str}"
                "\nInstruction: Use the previous chat history, or the context above, to interact and help the user."
            ),
            verbose=True,
        )
               
    def process_prompt(self, prompt):
        response = self.chat_engine.chat(prompt)
        return response.response

def _test_demo():
    llm = LLMProcessor()
    print(llm.process_prompt("Привет"))
    
_test_demo()
  

total size (MB): 4920.73


  0%|          | 10/4692 [00:13<2:24:22,  1.85s/it]